### ISSUE TITLE
ReadKey -1 is blocking (ActiveState/Windows7)

### ISSUE THREAD

**Issue by Theemim** [jonathanstowe/TermReadKey#28] opened 2017-07-03 08:14 UTC
On this system:
- ActiveState 5.24.1.2402 (x86) - fresh install, packages updated
- TermReadKey 2.37
- 64-bit Windows 7 Pro

I am seeing ReadKey(-1) block until a key is pressed.  Ideas?  Thank you.

```perl
use strict;
use warnings;
use Term::ReadKey;

$|=1;
print("\nStarting ReadKey blocking test.  Do not hit a key...\n");
testReadKey(1);   # ReadKey times out and returns undef as expected
testReadKey(-1);  # ReadKey blocks until a key is pressed
print("\nTest complete\n");

sub testReadKey {
  my $readKeyArg = shift;
  print("\nTesting \$key=ReadKey($readKeyArg) : ");
  ReadMode(4);
  my $key = ReadKey($readKeyArg);
  ReadMode(0);
  if(not defined $key) {
    print("\$key is undefined, test passed\n");
  }
  else {
    print("\$key is defined, test failed\n");
  }
}
```

**Comment by amba** [comment] 2017-07-03 08:31
Hey Theemim,
This might be related to recent issue #25.
The fix for this is not yet on CPAN.
In our case the workaround is to use the older 2.30 CPAN release.

**Comment by jonathanstowe** [comment] 2019-01-05 12:06
I'm going to close this now as I am unable to reproduce.  Please re-open with a PR if this is still problem.

**Closed by jonathanstowe** 2019-01-05 12:06 UTC
